[package]
name = "termfmt"
version = "0.1.9"
edition = "2021"
description = "Opinionated formatting for library primatives with color and outputing to the terminal."
license = "MIT"

[dependencies]
chrono = "0.4.38"
clap = "4.5.4"
eyre = "0.6.12"

[features]
command = []
layout = []
